name: Website

on:
  workflow_dispatch:
  push:
    #paths:
    #- "website/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2

      - name: âœ¨ Setup Hugo
        uses: peaceiris/actions-hugo@c03b5dbed22245418539b65eb9a3b1d5fdd9a0a6 # v2.5.0
        with:
          hugo-version: "0.92.2"

      - name: ğŸ› ï¸ Build
        run: hugo --source website --destination output --cleanDestinationDir --baseURL https://swharden.com/csdv/ --debug --minify

      - name: ğŸ”‘ Configure SSH
        uses: shimataro/ssh-key-action@3c9b0fc6f2d223b8450b02a0445f526350fc73e0 # v2.3.1
        with:
          key: ${{ secrets.REMOTE_SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: ğŸš€ Deploy
        run: rsync --archive --delete --stats -e 'ssh -p 18765' 'website/output/' ${{ secrets.REMOTE_DEST }}
